/*
 * Copyright 2021 Mandelsoft. All rights reserved.
 *  This file is licensed under the Apache Software License, v. 2 except as noted
 *  otherwise in the LICENSE file
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/mandelsoft/kubedyndns/apis/coredns/v1alpha1"
	corednsv1alpha1 "github.com/mandelsoft/kubedyndns/client/clientset/versioned/typed/coredns/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeHostedZones implements HostedZoneInterface
type fakeHostedZones struct {
	*gentype.FakeClientWithList[*v1alpha1.HostedZone, *v1alpha1.HostedZoneList]
	Fake *FakeCorednsV1alpha1
}

func newFakeHostedZones(fake *FakeCorednsV1alpha1, namespace string) corednsv1alpha1.HostedZoneInterface {
	return &fakeHostedZones{
		gentype.NewFakeClientWithList[*v1alpha1.HostedZone, *v1alpha1.HostedZoneList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("hostedzones"),
			v1alpha1.SchemeGroupVersion.WithKind("HostedZone"),
			func() *v1alpha1.HostedZone { return &v1alpha1.HostedZone{} },
			func() *v1alpha1.HostedZoneList { return &v1alpha1.HostedZoneList{} },
			func(dst, src *v1alpha1.HostedZoneList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.HostedZoneList) []*v1alpha1.HostedZone { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.HostedZoneList, items []*v1alpha1.HostedZone) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
