kind: CoreDNSEntry
apiVersion: coredns.mandelsoft.org/v1alpha1
metadata:
  name: demo
  namespace: default
spec:
  dnsNames:
  - demo.test.mandelsoft.org
  A:
  - 8.8.8.8
  TXT:
  - this is a test server
  SRV:
    service: dns
    records:
      - port: 53
        protocol: UDP
        priority: 10
        weight: 100
        host: dns.google.  # fqdn
      - port: 53
        protocol: UDP
        priority: 10
        weight: 100
        host: dns # relative dn
