/*
 * Copyright 2021 Mandelsoft. All rights reserved.
 *  This file is licensed under the Apache Software License, v. 2 except as noted
 *  otherwise in the LICENSE file
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/mandelsoft/kubedyndns/apis/coredns/v1alpha1"
	scheme "github.com/mandelsoft/kubedyndns/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CoreDNSEntriesGetter has a method to return a CoreDNSEntryInterface.
// A group's client should implement this interface.
type CoreDNSEntriesGetter interface {
	CoreDNSEntries(namespace string) CoreDNSEntryInterface
}

// CoreDNSEntryInterface has methods to work with CoreDNSEntry resources.
type CoreDNSEntryInterface interface {
	Create(ctx context.Context, coreDNSEntry *v1alpha1.CoreDNSEntry, opts v1.CreateOptions) (*v1alpha1.CoreDNSEntry, error)
	Update(ctx context.Context, coreDNSEntry *v1alpha1.CoreDNSEntry, opts v1.UpdateOptions) (*v1alpha1.CoreDNSEntry, error)
	UpdateStatus(ctx context.Context, coreDNSEntry *v1alpha1.CoreDNSEntry, opts v1.UpdateOptions) (*v1alpha1.CoreDNSEntry, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CoreDNSEntry, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CoreDNSEntryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CoreDNSEntry, err error)
	CoreDNSEntryExpansion
}

// coreDNSEntries implements CoreDNSEntryInterface
type coreDNSEntries struct {
	client rest.Interface
	ns     string
}

// newCoreDNSEntries returns a CoreDNSEntries
func newCoreDNSEntries(c *CorednsV1alpha1Client, namespace string) *coreDNSEntries {
	return &coreDNSEntries{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the coreDNSEntry, and returns the corresponding coreDNSEntry object, and an error if there is any.
func (c *coreDNSEntries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CoreDNSEntry, err error) {
	result = &v1alpha1.CoreDNSEntry{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("corednsentries").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CoreDNSEntries that match those selectors.
func (c *coreDNSEntries) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CoreDNSEntryList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CoreDNSEntryList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("corednsentries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested coreDNSEntries.
func (c *coreDNSEntries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("corednsentries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a coreDNSEntry and creates it.  Returns the server's representation of the coreDNSEntry, and an error, if there is any.
func (c *coreDNSEntries) Create(ctx context.Context, coreDNSEntry *v1alpha1.CoreDNSEntry, opts v1.CreateOptions) (result *v1alpha1.CoreDNSEntry, err error) {
	result = &v1alpha1.CoreDNSEntry{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("corednsentries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(coreDNSEntry).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a coreDNSEntry and updates it. Returns the server's representation of the coreDNSEntry, and an error, if there is any.
func (c *coreDNSEntries) Update(ctx context.Context, coreDNSEntry *v1alpha1.CoreDNSEntry, opts v1.UpdateOptions) (result *v1alpha1.CoreDNSEntry, err error) {
	result = &v1alpha1.CoreDNSEntry{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("corednsentries").
		Name(coreDNSEntry.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(coreDNSEntry).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *coreDNSEntries) UpdateStatus(ctx context.Context, coreDNSEntry *v1alpha1.CoreDNSEntry, opts v1.UpdateOptions) (result *v1alpha1.CoreDNSEntry, err error) {
	result = &v1alpha1.CoreDNSEntry{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("corednsentries").
		Name(coreDNSEntry.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(coreDNSEntry).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the coreDNSEntry and deletes it. Returns an error if one occurs.
func (c *coreDNSEntries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("corednsentries").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *coreDNSEntries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("corednsentries").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched coreDNSEntry.
func (c *coreDNSEntries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CoreDNSEntry, err error) {
	result = &v1alpha1.CoreDNSEntry{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("corednsentries").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
