/*
 * Copyright 2021 Mandelsoft. All rights reserved.
 *  This file is licensed under the Apache Software License, v. 2 except as noted
 *  otherwise in the LICENSE file
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	corednsv1alpha1 "github.com/mandelsoft/kubedyndns/apis/coredns/v1alpha1"
	scheme "github.com/mandelsoft/kubedyndns/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CoreDNSEntriesGetter has a method to return a CoreDNSEntryInterface.
// A group's client should implement this interface.
type CoreDNSEntriesGetter interface {
	CoreDNSEntries(namespace string) CoreDNSEntryInterface
}

// CoreDNSEntryInterface has methods to work with CoreDNSEntry resources.
type CoreDNSEntryInterface interface {
	Create(ctx context.Context, coreDNSEntry *corednsv1alpha1.CoreDNSEntry, opts v1.CreateOptions) (*corednsv1alpha1.CoreDNSEntry, error)
	Update(ctx context.Context, coreDNSEntry *corednsv1alpha1.CoreDNSEntry, opts v1.UpdateOptions) (*corednsv1alpha1.CoreDNSEntry, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, coreDNSEntry *corednsv1alpha1.CoreDNSEntry, opts v1.UpdateOptions) (*corednsv1alpha1.CoreDNSEntry, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*corednsv1alpha1.CoreDNSEntry, error)
	List(ctx context.Context, opts v1.ListOptions) (*corednsv1alpha1.CoreDNSEntryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *corednsv1alpha1.CoreDNSEntry, err error)
	CoreDNSEntryExpansion
}

// coreDNSEntries implements CoreDNSEntryInterface
type coreDNSEntries struct {
	*gentype.ClientWithList[*corednsv1alpha1.CoreDNSEntry, *corednsv1alpha1.CoreDNSEntryList]
}

// newCoreDNSEntries returns a CoreDNSEntries
func newCoreDNSEntries(c *CorednsV1alpha1Client, namespace string) *coreDNSEntries {
	return &coreDNSEntries{
		gentype.NewClientWithList[*corednsv1alpha1.CoreDNSEntry, *corednsv1alpha1.CoreDNSEntryList](
			"corednsentries",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *corednsv1alpha1.CoreDNSEntry { return &corednsv1alpha1.CoreDNSEntry{} },
			func() *corednsv1alpha1.CoreDNSEntryList { return &corednsv1alpha1.CoreDNSEntryList{} },
		),
	}
}
