/*
 * Copyright 2021 Mandelsoft. All rights reserved.
 *  This file is licensed under the Apache Software License, v. 2 except as noted
 *  otherwise in the LICENSE file
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	corednsv1alpha1 "github.com/mandelsoft/kubedyndns/apis/coredns/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// HostedZoneLister helps list HostedZones.
// All objects returned here must be treated as read-only.
type HostedZoneLister interface {
	// List lists all HostedZones in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corednsv1alpha1.HostedZone, err error)
	// HostedZones returns an object that can list and get HostedZones.
	HostedZones(namespace string) HostedZoneNamespaceLister
	HostedZoneListerExpansion
}

// hostedZoneLister implements the HostedZoneLister interface.
type hostedZoneLister struct {
	listers.ResourceIndexer[*corednsv1alpha1.HostedZone]
}

// NewHostedZoneLister returns a new HostedZoneLister.
func NewHostedZoneLister(indexer cache.Indexer) HostedZoneLister {
	return &hostedZoneLister{listers.New[*corednsv1alpha1.HostedZone](indexer, corednsv1alpha1.Resource("hostedzone"))}
}

// HostedZones returns an object that can list and get HostedZones.
func (s *hostedZoneLister) HostedZones(namespace string) HostedZoneNamespaceLister {
	return hostedZoneNamespaceLister{listers.NewNamespaced[*corednsv1alpha1.HostedZone](s.ResourceIndexer, namespace)}
}

// HostedZoneNamespaceLister helps list and get HostedZones.
// All objects returned here must be treated as read-only.
type HostedZoneNamespaceLister interface {
	// List lists all HostedZones in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*corednsv1alpha1.HostedZone, err error)
	// Get retrieves the HostedZone from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*corednsv1alpha1.HostedZone, error)
	HostedZoneNamespaceListerExpansion
}

// hostedZoneNamespaceLister implements the HostedZoneNamespaceLister
// interface.
type hostedZoneNamespaceLister struct {
	listers.ResourceIndexer[*corednsv1alpha1.HostedZone]
}
